### ISSUE TITLE
idb.js bugs

### ISSUE THREAD

**Issue by inexorabletash** [scaljeri/indexeddb-vs-websql#1]
``` js
for (var i = 0; i < db.objectStoreNames.length; i ++) {
  console.info('delete object store: ' + db.objectStoreNames[i]) ;
  db.deleteObjectStore(db.objectStoreNames[i]);
}
```

This will fail for multiple stores, as length will decrease as the stores are deleted while the counter will be incremented. You probably want:

``` js
while (db.objectStoreNames.length)
  db.deleteObjectStore(db.objectStoreNames[0]);
```

And the test overall will only test prefixed versions of the API:

``` js
idb = getIndexedDBObject( 'IndexedDB' ) ;

function getIndexedDBObject(name) {
  return window[name] || window['webkit' + name] || window['moz' + name] || window['ms' + name] ;
}
```

That will attempt to use `window.IndexedDB` but the standard API entry point is `window.indexedDB` so this always falls back to a prefixed version, and will break if they are removed.

**Comment by scaljeri** [comment]
Thnx for pointing that out. I'll fix that! But I think that code needs a re-write anyway :)
